using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Game.Maps
{
    class Canyon
    {
        public static Items.Item.ItemType[, ,] Get()
        {
            Items.Item.ItemType[, ,] MapPart = new Items.Item.ItemType[,,] { 
           { { Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass } },
            { { Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock } },
            { { Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass } },
            { { Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock } },
            { { Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock } },
            { { Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass } },
            { { Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass } },
            { { Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass } },
            { { Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass } },
            { { Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass } },
            { { Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock } },
            { { Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock } },
            { { Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock } },
            { { Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Rock, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass } },
            };

            return MapPart;
        }
    }
}
