using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Game.Actions;

namespace Game.Maps
{
    public class Start
    {
        public static Items.Item.ItemType[, ,] Get()
        {
            Items.Item.ItemType[, ,] Room = new Items.Item.ItemType[,,] { 

          { { Items.Item.ItemType.Tree, Items.Item.ItemType.Flower2, Items.Item.ItemType.Flower2, Items.Item.ItemType.Water, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Water, Items.Item.ItemType.Flower2, Items.Item.ItemType.Flower2, Items.Item.ItemType.Tree, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass } },
{ { Items.Item.ItemType.Flower2, Items.Item.ItemType.Water, Items.Item.ItemType.Water, Items.Item.ItemType.Water, Items.Item.ItemType.Path, Items.Item.ItemType.WarpPad, Items.Item.ItemType.Path, Items.Item.ItemType.Water, Items.Item.ItemType.Water, Items.Item.ItemType.Water, Items.Item.ItemType.Flower2, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass } },
{ { Items.Item.ItemType.Flower2, Items.Item.ItemType.Water, Items.Item.ItemType.Lava, Items.Item.ItemType.Wall, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Wall, Items.Item.ItemType.Lava, Items.Item.ItemType.Water, Items.Item.ItemType.Flower2, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass } },
{ { Items.Item.ItemType.Water, Items.Item.ItemType.Water, Items.Item.ItemType.Wall, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Wall, Items.Item.ItemType.Water, Items.Item.ItemType.Water, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass } },
{ { Items.Item.ItemType.Grass, Items.Item.ItemType.Path, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Path, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass } },
{ { Items.Item.ItemType.Grass, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass } },
{ { Items.Item.ItemType.Grass, Items.Item.ItemType.Path, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Path, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass } },
{ { Items.Item.ItemType.Water, Items.Item.ItemType.Water, Items.Item.ItemType.Wall, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Wall, Items.Item.ItemType.Water, Items.Item.ItemType.Water, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass } },
{ { Items.Item.ItemType.Flower2, Items.Item.ItemType.Water, Items.Item.ItemType.Lava, Items.Item.ItemType.Wall, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Floor, Items.Item.ItemType.Wall, Items.Item.ItemType.Lava, Items.Item.ItemType.Water, Items.Item.ItemType.Flower2, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass } },
{ { Items.Item.ItemType.Flower2, Items.Item.ItemType.Water, Items.Item.ItemType.Water, Items.Item.ItemType.Water, Items.Item.ItemType.Path, Items.Item.ItemType.Floor, Items.Item.ItemType.Path, Items.Item.ItemType.Water, Items.Item.ItemType.Water, Items.Item.ItemType.Water, Items.Item.ItemType.Flower2, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass } },
{ { Items.Item.ItemType.Tree, Items.Item.ItemType.Flower2, Items.Item.ItemType.Flower2, Items.Item.ItemType.Water, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Water, Items.Item.ItemType.Flower2, Items.Item.ItemType.Flower2, Items.Item.ItemType.Tree, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass, Items.Item.ItemType.Grass } },
            
            
            
            };
            return Room;
        }
    }
}
